### ISSUE TITLE
Error processing PDF: Command failed with exit code 2

### ISSUE THREAD

**Issue by aman977** [mgmeyers/obsidian-zotero-integration#300]
Hi, 

I am having an issue extracting notes from one particular article.T

The message I get is as below:
Error processing PDF: Command failed with
exit code 2:
C:\Users\maharjan\Aman\aman-PKM\PhD-va
ult\.obsidian\plugins\obsidian-zotero-
desktop-connector\pdfannots2json.exe
C:\Users\maharjan\Aman\aman_PKM\Bibliog
raphy\storage\K8BTERUT\Shadmehr et al. -
2016 - A Representation of Effort in
Decision-Making and .pdf -n
Shadmehr2016RepresentationEffortDecision
Making -d 120 -f jpg -o
C:\Users\maharjan\Aman\aman_PKM\PhD_va
ult\04-Archives\04-Annotation-Notes\Zoter
o\Shadmehr2016RepresentationEffortDecisi
onMaking -q 90
panic: runtime error: index out of range [11]
with length 11
goroutine 1 [running]:
github.com/softlandia/cpd.DecodeUTF16be(
{Oxc0003df7f2, Oxd})

Thank you in advance.

**Comment by DanielRunningen** [comment]
Encountering this error a year later.

```
Error: Command failed with exit code 2: /Vault/.obsidian/plugins/obsidian-zotero-desktop-connector/pdfannots2json-linux-x64 /Zotero/storage/KF8RAPU2/Göçmen and Coşkun - 2019 - The effects of the six thinking hats and speed on creativity in brainstorming.pdf -w -n base_name -d 120 -f jpg -o /Documents/output_path -q 90
panic: runtime error: index out of range [157] with length 157

goroutine 1 [running]:
github.com/softlandia/cpd.DecodeUTF16be({0xc00034adc0, 0x9f})
	github.com/softlandia/cpd@v1.0.0/utf16be.go:23 +0x2d2
github.com/mgmeyers/unipdf/v3/core.MakeString({0xc00034adc0, 0x9f})
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/primitives.go:174 +0x85
github.com/mgmeyers/unipdf/v3/core.(*PdfParser).parseString(0xc0001ae6c0)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/parser.go:373 +0x3d1
github.com/mgmeyers/unipdf/v3/core.(*PdfParser).parseObject(0xc0001ae6c0)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/parser.go:509 +0x946
github.com/mgmeyers/unipdf/v3/core.(*PdfParser).ParseDict(0xc0001ae6c0)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/parser.go:636 +0x669
github.com/mgmeyers/unipdf/v3/core.(*PdfParser).ParseIndirectObject(0xc0001ae6c0)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/parser.go:1472 +0x87c
github.com/mgmeyers/unipdf/v3/core.(*PdfParser).lookupByNumber(0xc0001ae6c0, 0x11f, 0x1)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/crossrefs.go:265 +0x9b3
github.com/mgmeyers/unipdf/v3/core.(*PdfParser).lookupByNumberWrapper(0xc0001ae6c0, 0xcd41d2?, 0x80?)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/crossrefs.go:208 +0x25
github.com/mgmeyers/unipdf/v3/core.(*PdfParser).LookupByNumber(...)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/crossrefs.go:202
github.com/mgmeyers/unipdf/v3/core.(*PdfParser).LookupByReference(0xc484c0?, {0xc0001ae6c0, 0x11f, 0x0})
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/crossrefs.go:338 +0x139
github.com/mgmeyers/unipdf/v3/core.(*PdfParser).resolveReference(0xc0001ae6c0, 0xc00000e390)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/parser.go:1661 +0x65
github.com/mgmeyers/unipdf/v3/core.(*PdfObjectReference).Resolve(0xc3da60?)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/primitives.go:265 +0x34
github.com/mgmeyers/unipdf/v3/core.ResolveReference(...)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/core/utils.go:61
github.com/mgmeyers/unipdf/v3/model.(*PdfReader).buildOutlineTree(0xd8fd30?, {0xd8fd30?, 0xc00039d5c0}, 0x0, 0x0, 0xc00000e318?)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/model/reader.go:381 +0x826
github.com/mgmeyers/unipdf/v3/model.(*PdfReader).loadOutlines(0xc0001cd860)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/model/reader.go:301 +0x31d
github.com/mgmeyers/unipdf/v3/model.(*PdfReader).loadStructure(0xc0001cd860)
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/model/reader.go:246 +0x709
github.com/mgmeyers/unipdf/v3/model.NewPdfReader({0xd91068?, 0xc0000102c8})
	github.com/mgmeyers/unipdf/v3@v3.9.0-1/model/reader.go:71 +0x165
main.main()
	github.com/mgmeyers/pdfannots2json/main.go:87 +0x267
    at $i (plugin:obsidian-zotero-desktop-connector:51:57)
    at eval (plugin:obsidian-zotero-desktop-connector:52:1356)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async yp (plugin:obsidian-zotero-desktop-connector:123:1096)
    at async Kx (plugin:obsidian-zotero-desktop-connector:126:5099)
```

It's the only document I have that does this. It's also the only document that I have that was processed by RapidX through my university library, which makes me wonder if it has to do with the file encoding to prevent reproduction and distribution. Not even the data explorer can open the item, but if I make a copy of the item that doesn't have the PDF, everything is fine.

I'm not sure if there's a way to still do the import from the parent item even if the PDF itself causes problems.
